// Code generated by MockGen. DO NOT EDIT.
// Source: internal/db/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/db/repository.go -destination=internal/mocks/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	db "github.com/anmol420/p2p-payment-ledger/internal/db"
	pgtype "github.com/jackc/pgx/v5/pgtype"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AcquireAdvisoryLock mocks base method.
func (m *MockRepository) AcquireAdvisoryLock(ctx context.Context, pgAdvisoryXactLock int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcquireAdvisoryLock", ctx, pgAdvisoryXactLock)
	ret0, _ := ret[0].(error)
	return ret0
}

// AcquireAdvisoryLock indicates an expected call of AcquireAdvisoryLock.
func (mr *MockRepositoryMockRecorder) AcquireAdvisoryLock(ctx, pgAdvisoryXactLock any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcquireAdvisoryLock", reflect.TypeOf((*MockRepository)(nil).AcquireAdvisoryLock), ctx, pgAdvisoryXactLock)
}

// CreateAccount mocks base method.
func (m *MockRepository) CreateAccount(ctx context.Context, arg db.CreateAccountParams) (db.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccount", ctx, arg)
	ret0, _ := ret[0].(db.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockRepositoryMockRecorder) CreateAccount(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockRepository)(nil).CreateAccount), ctx, arg)
}

// CreateAuditEntry mocks base method.
func (m *MockRepository) CreateAuditEntry(ctx context.Context, arg db.CreateAuditEntryParams) (db.AuditLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAuditEntry", ctx, arg)
	ret0, _ := ret[0].(db.AuditLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAuditEntry indicates an expected call of CreateAuditEntry.
func (mr *MockRepositoryMockRecorder) CreateAuditEntry(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAuditEntry", reflect.TypeOf((*MockRepository)(nil).CreateAuditEntry), ctx, arg)
}

// CreateTransaction mocks base method.
func (m *MockRepository) CreateTransaction(ctx context.Context, arg db.CreateTransactionParams) (db.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransaction", ctx, arg)
	ret0, _ := ret[0].(db.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTransaction indicates an expected call of CreateTransaction.
func (mr *MockRepositoryMockRecorder) CreateTransaction(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransaction", reflect.TypeOf((*MockRepository)(nil).CreateTransaction), ctx, arg)
}

// ExecTx mocks base method.
func (m *MockRepository) ExecTx(arg0 context.Context, arg1 func(db.Querier) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecTx", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecTx indicates an expected call of ExecTx.
func (mr *MockRepositoryMockRecorder) ExecTx(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecTx", reflect.TypeOf((*MockRepository)(nil).ExecTx), arg0, arg1)
}

// GetAccount mocks base method.
func (m *MockRepository) GetAccount(ctx context.Context, id pgtype.UUID) (db.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccount", ctx, id)
	ret0, _ := ret[0].(db.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccount indicates an expected call of GetAccount.
func (mr *MockRepositoryMockRecorder) GetAccount(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccount", reflect.TypeOf((*MockRepository)(nil).GetAccount), ctx, id)
}

// GetAccountForUpdate mocks base method.
func (m *MockRepository) GetAccountForUpdate(ctx context.Context, id pgtype.UUID) (db.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountForUpdate", ctx, id)
	ret0, _ := ret[0].(db.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountForUpdate indicates an expected call of GetAccountForUpdate.
func (mr *MockRepositoryMockRecorder) GetAccountForUpdate(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountForUpdate", reflect.TypeOf((*MockRepository)(nil).GetAccountForUpdate), ctx, id)
}

// GetTransaction mocks base method.
func (m *MockRepository) GetTransaction(ctx context.Context, id pgtype.UUID) (db.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransaction", ctx, id)
	ret0, _ := ret[0].(db.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransaction indicates an expected call of GetTransaction.
func (mr *MockRepositoryMockRecorder) GetTransaction(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransaction", reflect.TypeOf((*MockRepository)(nil).GetTransaction), ctx, id)
}

// GetTransactionByIdempotencyKey mocks base method.
func (m *MockRepository) GetTransactionByIdempotencyKey(ctx context.Context, idempotencyKey string) (db.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionByIdempotencyKey", ctx, idempotencyKey)
	ret0, _ := ret[0].(db.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionByIdempotencyKey indicates an expected call of GetTransactionByIdempotencyKey.
func (mr *MockRepositoryMockRecorder) GetTransactionByIdempotencyKey(ctx, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionByIdempotencyKey", reflect.TypeOf((*MockRepository)(nil).GetTransactionByIdempotencyKey), ctx, idempotencyKey)
}

// ListAccounts mocks base method.
func (m *MockRepository) ListAccounts(ctx context.Context, arg db.ListAccountsParams) ([]db.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccounts", ctx, arg)
	ret0, _ := ret[0].([]db.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAccounts indicates an expected call of ListAccounts.
func (mr *MockRepositoryMockRecorder) ListAccounts(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccounts", reflect.TypeOf((*MockRepository)(nil).ListAccounts), ctx, arg)
}

// ListAuditLogByAccount mocks base method.
func (m *MockRepository) ListAuditLogByAccount(ctx context.Context, arg db.ListAuditLogByAccountParams) ([]db.AuditLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAuditLogByAccount", ctx, arg)
	ret0, _ := ret[0].([]db.AuditLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAuditLogByAccount indicates an expected call of ListAuditLogByAccount.
func (mr *MockRepositoryMockRecorder) ListAuditLogByAccount(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAuditLogByAccount", reflect.TypeOf((*MockRepository)(nil).ListAuditLogByAccount), ctx, arg)
}

// ListTransactionsByAccount mocks base method.
func (m *MockRepository) ListTransactionsByAccount(ctx context.Context, arg db.ListTransactionsByAccountParams) ([]db.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransactionsByAccount", ctx, arg)
	ret0, _ := ret[0].([]db.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTransactionsByAccount indicates an expected call of ListTransactionsByAccount.
func (mr *MockRepositoryMockRecorder) ListTransactionsByAccount(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransactionsByAccount", reflect.TypeOf((*MockRepository)(nil).ListTransactionsByAccount), ctx, arg)
}

// ListTransactionsByAccountCursor mocks base method.
func (m *MockRepository) ListTransactionsByAccountCursor(ctx context.Context, arg db.ListTransactionsByAccountCursorParams) ([]db.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransactionsByAccountCursor", ctx, arg)
	ret0, _ := ret[0].([]db.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTransactionsByAccountCursor indicates an expected call of ListTransactionsByAccountCursor.
func (mr *MockRepositoryMockRecorder) ListTransactionsByAccountCursor(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransactionsByAccountCursor", reflect.TypeOf((*MockRepository)(nil).ListTransactionsByAccountCursor), ctx, arg)
}

// UpdateAccountBalance mocks base method.
func (m *MockRepository) UpdateAccountBalance(ctx context.Context, arg db.UpdateAccountBalanceParams) (db.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccountBalance", ctx, arg)
	ret0, _ := ret[0].(db.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAccountBalance indicates an expected call of UpdateAccountBalance.
func (mr *MockRepositoryMockRecorder) UpdateAccountBalance(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccountBalance", reflect.TypeOf((*MockRepository)(nil).UpdateAccountBalance), ctx, arg)
}

// UpdateTransactionStatus mocks base method.
func (m *MockRepository) UpdateTransactionStatus(ctx context.Context, arg db.UpdateTransactionStatusParams) (db.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTransactionStatus", ctx, arg)
	ret0, _ := ret[0].(db.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTransactionStatus indicates an expected call of UpdateTransactionStatus.
func (mr *MockRepositoryMockRecorder) UpdateTransactionStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTransactionStatus", reflect.TypeOf((*MockRepository)(nil).UpdateTransactionStatus), ctx, arg)
}
