// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireAdvisoryLock = `-- name: AcquireAdvisoryLock :exec
SELECT pg_advisory_xact_lock($1)
`

func (q *Queries) AcquireAdvisoryLock(ctx context.Context, pgAdvisoryXactLock int64) error {
	_, err := q.db.Exec(ctx, acquireAdvisoryLock, pgAdvisoryXactLock)
	return err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    owner_name,
    balance
) VALUES (
    $1, $2
)
RETURNING id, owner_name, balance, created_at, updated_at
`

type CreateAccountParams struct {
	OwnerName string `json:"owner_name"`
	Balance   int64  `json:"balance"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.OwnerName, arg.Balance)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.OwnerName,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAuditEntry = `-- name: CreateAuditEntry :one
INSERT INTO audit_log (
    account_id,
    transaction_id,
    event_type,
    amount,
    balance_before,
    balance_after
) VALUES (
          $1, $2, $3, $4, $5, $6
)
RETURNING id, account_id, transaction_id, event_type, amount, balance_before, balance_after, created_at
`

type CreateAuditEntryParams struct {
	AccountID     pgtype.UUID    `json:"account_id"`
	TransactionID pgtype.UUID    `json:"transaction_id"`
	EventType     AuditEventType `json:"event_type"`
	Amount        int64          `json:"amount"`
	BalanceBefore int64          `json:"balance_before"`
	BalanceAfter  int64          `json:"balance_after"`
}

func (q *Queries) CreateAuditEntry(ctx context.Context, arg CreateAuditEntryParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditEntry,
		arg.AccountID,
		arg.TransactionID,
		arg.EventType,
		arg.Amount,
		arg.BalanceBefore,
		arg.BalanceAfter,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TransactionID,
		&i.EventType,
		&i.Amount,
		&i.BalanceBefore,
		&i.BalanceAfter,
		&i.CreatedAt,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    idempotency_key,
    from_account_id,
    to_account_id,
    amount,
    status
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, idempotency_key, from_account_id, to_account_id, amount, status, created_at
`

type CreateTransactionParams struct {
	IdempotencyKey string            `json:"idempotency_key"`
	FromAccountID  pgtype.UUID       `json:"from_account_id"`
	ToAccountID    pgtype.UUID       `json:"to_account_id"`
	Amount         int64             `json:"amount"`
	Status         TransactionStatus `json:"status"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.IdempotencyKey,
		arg.FromAccountID,
		arg.ToAccountID,
		arg.Amount,
		arg.Status,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, owner_name, balance, created_at, updated_at FROM accounts
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetAccount(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.OwnerName,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountForUpdate = `-- name: GetAccountForUpdate :one
SELECT id, owner_name, balance, created_at, updated_at FROM accounts
WHERE id = $1
LIMIT 1
FOR NO KEY UPDATE
`

func (q *Queries) GetAccountForUpdate(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountForUpdate, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.OwnerName,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, idempotency_key, from_account_id, to_account_id, amount, status, created_at FROM transactions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetTransaction(ctx context.Context, id pgtype.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getTransactionByIdempotencyKey = `-- name: GetTransactionByIdempotencyKey :one
SELECT id, idempotency_key, from_account_id, to_account_id, amount, status, created_at FROM transactions
WHERE idempotency_key = $1
LIMIT 1
`

func (q *Queries) GetTransactionByIdempotencyKey(ctx context.Context, idempotencyKey string) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByIdempotencyKey, idempotencyKey)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, owner_name, balance, created_at, updated_at FROM accounts
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAccountsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccounts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.OwnerName,
			&i.Balance,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogByAccount = `-- name: ListAuditLogByAccount :many
SELECT id, account_id, transaction_id, event_type, amount, balance_before, balance_after, created_at FROM audit_log
WHERE account_id = $1
  AND (
    $2::boolean = false
    OR (created_at, id) < ($3::timestamptz, $4::uuid)
    )
ORDER BY created_at DESC, id DESC
    LIMIT $5
`

type ListAuditLogByAccountParams struct {
	AccountID  pgtype.UUID        `json:"account_id"`
	UseCursor  bool               `json:"use_cursor"`
	CursorTime pgtype.Timestamptz `json:"cursor_time"`
	CursorID   pgtype.UUID        `json:"cursor_id"`
	LimitCount int32              `json:"limit_count"`
}

func (q *Queries) ListAuditLogByAccount(ctx context.Context, arg ListAuditLogByAccountParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogByAccount,
		arg.AccountID,
		arg.UseCursor,
		arg.CursorTime,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TransactionID,
			&i.EventType,
			&i.Amount,
			&i.BalanceBefore,
			&i.BalanceAfter,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByAccount = `-- name: ListTransactionsByAccount :many
SELECT id, idempotency_key, from_account_id, to_account_id, amount, status, created_at FROM transactions
WHERE from_account_id = $1
    OR to_account_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsByAccountParams struct {
	FromAccountID pgtype.UUID `json:"from_account_id"`
	Limit         int32       `json:"limit"`
	Offset        int32       `json:"offset"`
}

func (q *Queries) ListTransactionsByAccount(ctx context.Context, arg ListTransactionsByAccountParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByAccount, arg.FromAccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.IdempotencyKey,
			&i.FromAccountID,
			&i.ToAccountID,
			&i.Amount,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByAccountCursor = `-- name: ListTransactionsByAccountCursor :many
SELECT id, idempotency_key, from_account_id, to_account_id, amount, status, created_at FROM transactions
WHERE (from_account_id = $1 OR to_account_id = $1)
  AND (
    $2::boolean = false
    OR (created_at, id) < ($3::timestamptz, $4::uuid)
    )
ORDER BY created_at DESC, id DESC
    LIMIT $5
`

type ListTransactionsByAccountCursorParams struct {
	AccountID  pgtype.UUID        `json:"account_id"`
	UseCursor  bool               `json:"use_cursor"`
	CursorTime pgtype.Timestamptz `json:"cursor_time"`
	CursorID   pgtype.UUID        `json:"cursor_id"`
	LimitCount int32              `json:"limit_count"`
}

func (q *Queries) ListTransactionsByAccountCursor(ctx context.Context, arg ListTransactionsByAccountCursorParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByAccountCursor,
		arg.AccountID,
		arg.UseCursor,
		arg.CursorTime,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.IdempotencyKey,
			&i.FromAccountID,
			&i.ToAccountID,
			&i.Amount,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountBalance = `-- name: UpdateAccountBalance :one
UPDATE accounts
SET
    balance = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, owner_name, balance, created_at, updated_at
`

type UpdateAccountBalanceParams struct {
	ID      pgtype.UUID `json:"id"`
	Balance int64       `json:"balance"`
}

func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccountBalance, arg.ID, arg.Balance)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.OwnerName,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTransactionStatus = `-- name: UpdateTransactionStatus :one
UPDATE transactions
SET status = $2
WHERE id = $1
RETURNING id, idempotency_key, from_account_id, to_account_id, amount, status, created_at
`

type UpdateTransactionStatusParams struct {
	ID     pgtype.UUID       `json:"id"`
	Status TransactionStatus `json:"status"`
}

func (q *Queries) UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransactionStatus, arg.ID, arg.Status)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
